"""Build deploy/app.env: the secrets file for the server, from your local .env.

Only the variables the app actually reads (the fields of app.config.Settings) are copied, so
things that live in your local .env for other reasons (the Supabase database password and
secret key, the WhatsApp business account id, ...) never reach the server. Values are written
so that Docker Compose reads them back exactly as they are, whatever characters they contain.

  python scripts/make_app_env.py
  python scripts/make_app_env.py --source path/to/.env --out deploy/app.env

Prints variable NAMES only, never values. The output is git-ignored.
"""

import argparse
import sys
from pathlib import Path

from dotenv import dotenv_values

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from app.config import Settings  # noqa: E402

# The bot refuses to be useful without these.
REQUIRED = [
    "WA_PHONE_NUMBER_ID", "WA_TOKEN", "WA_VERIFY_TOKEN", "WA_APP_SECRET",
    "GEMINI_API_KEY", "GEMINI_MODEL", "GEMINI_EMBED_MODEL",
    "ELEVENLABS_API_KEY", "TAVILY_API_KEY", "GROQ_API_KEY",
    "SUPABASE_URL", "SUPABASE_SERVICE_KEY", "PHONE_HASH_SALT",
]


def quote(value: str) -> str:
    """Single quotes are taken literally by Compose (no ${} expansion, no comment parsing)."""
    if "\n" in value or "\r" in value:
        raise ValueError("a value contains a line break")
    if "'" in value:
        raise ValueError("a value contains a single quote")
    return f"'{value}'"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--source", default=str(ROOT / ".env"))
    ap.add_argument("--out", default=str(ROOT / "deploy" / "app.env"))
    args = ap.parse_args()

    source = dotenv_values(args.source)
    wanted = list(Settings.model_fields)
    copied, empty, skipped = [], [], []
    lines = ["# Generated by scripts/make_app_env.py: the bot's secrets. Never commit this file."]

    for name in wanted:
        value = source.get(name)
        if value is None or value == "":
            empty.append(name)
            continue
        try:
            lines.append(f"{name}={quote(value)}")
        except ValueError as exc:
            skipped.append(f"{name} ({exc})")
            continue
        copied.append(name)

    left_out = sorted(k for k in source if k not in wanted)
    missing = [n for n in REQUIRED if n not in copied]

    Path(args.out).write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"Wrote {args.out}")
    print(f"  copied {len(copied)}: {', '.join(copied)}")
    print(f"  left out because the app never reads them ({len(left_out)}): {', '.join(left_out) or 'none'}")
    print(f"  unset (the app's defaults apply): {', '.join(empty) or 'none'}")
    if skipped:
        print(f"  NOT copied, needs a manual fix: {', '.join(skipped)}")
    if missing:
        print(f"\nERROR: required variables are missing or empty: {', '.join(missing)}")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
